# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41

---
include:
  # Aurora Corne
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: aurora_corne_left
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right nice_view_adapter nice_view
    artifact-name: aurora_corne_right

  # Kyria
  - board: nice_nano_v2
    shield: kyria_left
    artifact-name: kyria_1_4_left
  - board: nice_nano_v2
    shield: kyria_right
    artifact-name: kyria_1_4_right

  # Aurora Corne Reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne_reset
